# Application Configuration
spring.application.name=leave-management-system
server.port=8080

# Database Configuration (MongoDB)
# IMPORTANT: Replace <db_password> with your actual database password
spring.data.mongodb.uri=mongodb://mohankrishna0715_db_user:Mohan@ac-o4oyt2n-shard-00-00.afdkfam.mongodb.net:27017,ac-o4oyt2n-shard-00-01.afdkfam.mongodb.net:27017,ac-o4oyt2n-shard-00-02.afdkfam.mongodb.net:27017/?ssl=true&replicaSet=atlas-xbbro9-shard-0&authSource=admin&appName=Cluster0
spring.data.mongodb.database=leave_management_db
# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351
jwt.expiration=86400000
